# -*- coding: utf-8 -*-
"""JSONB BD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIVuJHXNo5mTAO0KJuytCMXHvHnv2E2G
"""

!pip install psycopg2-binary

"""Conexão Neon:"""

import psycopg2

conn = psycopg2.connect(
    host="ep-proud-credit-apggyrpp-pooler.c-7.us-east-1.aws.neon.tech",
    dbname="neondb",
    user="neondb_owner",
    password="npg_ElmJWobD06je",
    port="5432",
    sslmode="require"
)

print("Conectado!")

cur = conn.cursor()

cur.execute("SELECT version();")

print(cur.fetchone())

cur.execute("""
CREATE EXTENSION IF NOT EXISTS pgcrypto;
""")

conn.commit()

"""Criação da tabela:"""

conn.rollback()
cur.execute("""
CREATE TABLE IF NOT EXISTS produtos (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    detalhes JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
""")

conn.commit()

"""Inserindo os produtos:"""

cur.execute("""
INSERT INTO produtos(nome, detalhes)
VALUES (
'Notebook Gamer',
'{
    "categoria":"computador",
    "ram":"16GB",
    "processador":"Ryzen 7",
    "ssd":"512GB"
}'
);
""")

conn.commit()

cur.execute("""
SELECT * FROM produtos;
""")

for linha in cur.fetchall():
    print(linha)

import json
import psycopg2 # Import psycopg2 again for re-connection

# Re-establish connection as it was closed
conn = psycopg2.connect(
    host="ep-proud-credit-apggyrpp-pooler.c-7.us-east-1.aws.neon.tech",
    dbname="neondb",
    user="neondb_owner",
    password="npg_ElmJWobD06je",
    port="5432",
    sslmode="require"
)

# Re-create cursor to ensure it's open and valid for new operations
cur = conn.cursor()

produtos = [
    (
        "Celular Galaxy A55",
        {
            "categoria": "celular",
            "preco": 2500,
            "estoque": 18,
            "especificacoes": {
                "tela": "6.5",
                "camera": "50MP",
                "memoria": "128GB"
            },
            "tags": ["android", "5g", "smartphone"],
            "avaliacoes": [
                {"usuario": "Ana", "nota": 5},
                {"usuario": "Carlos", "nota": 4}
            ]
        }
    ),
    (
        "Tablet Pro 11",
        {
            "categoria": "tablet",
            "preco": 3200,
            "estoque": 9,
            "especificacoes": {
                "tela": "11",
                "armazenamento": "256GB",
                "caneta": True
            },
            "tags": ["tablet", "estudo", "trabalho"],
            "avaliacoes": [
                {"usuario": "Bia", "nota": 5},
                {"usuario": "Joao", "nota": 4}
            ]
        }
    ),
    (
        "SSD Kingston 1TB",
        {
            "categoria": "armazenamento",
            "preco": 450,
            "estoque": 35,
            "especificacoes": {
                "tipo": "SSD",
                "capacidade": "1TB",
                "interface": "NVMe"
            },
            "tags": ["ssd", "rapido", "pc"],
            "avaliacoes": [
                {"usuario": "Marta", "nota": 5}
            ]
        }
    ),
    (
        "Monitor Ultra 27",
        {
            "categoria": "monitor",
            "preco": 1200,
            "estoque": 11,
            "especificacoes": {
                "tamanho": "27",
                "resolucao": "4K",
                "taxa_atualizacao": "144Hz"
            },
            "tags": ["monitor", "4k", "gaming"],
            "avaliacoes": [
                {"usuario": "Paulo", "nota": 5},
                {"usuario": "Rafa", "nota": 4}
            ]
        }
    ),
    (
        "Teclado Mecânico MK1",
        {
            "categoria": "periferico",
            "preco": 380,
            "estoque": 22,
            "especificacoes": {
                "layout": "ABNT2",
                "switch": "Blue",
                "retroiluminacao": True
            },
            "tags": ["teclado", "mecanico", "gamer"],
            "avaliacoes": [
                {"usuario": "Lia", "nota": 5}
            ]
        }
    ),
    (
        "Mouse Gamer G203",
        {
            "categoria": "periferico",
            "preco": 180,
            "estoque": 40,
            "especificacoes": {
                "dpi": 8000,
                "botões": 6,
                "conexao": "USB"
            },
            "tags": ["mouse", "gamer", "usb"],
            "avaliacoes": [
                {"usuario": "Nina", "nota": 4},
                {"usuario": "Pedro", "nota": 5}
            ]
        }
    ),
    (
        "Fone Bluetooth Wave",
        {
            "categoria": "audio",
            "preco": 260,
            "estoque": 28,
            "especificacoes": {
                "bateria": "30h",
                "cancelamento_ruido": True,
                "microfone": True
            },
            "tags": ["fone", "bluetooth", "audio"],
            "avaliacoes": [
                {"usuario": "Duda", "nota": 5}
            ]
        }
    ),
    (
        "Roteador AX3000",
        {
            "categoria": "rede",
            "preco": 520,
            "estoque": 14,
            "especificacoes": {
                "wifi": "6",
                "velocidade": "3000Mbps",
                "antenas": 4
            },
            "tags": ["roteador", "wifi6", "internet"],
            "avaliacoes": [
                {"usuario": "Bruna", "nota": 4}
            ]
        }
    ),
    (
        "Smartwatch Fit Pro",
        {
            "categoria": "wearable",
            "preco": 890,
            "estoque": 16,
            "especificacoes": {
                "bateria": "7d",
                "gps": True,
                "resistencia_agua": "5ATM"
            },
            "tags": ["relógio", "fitness", "smartwatch"],
            "avaliacoes": [
                {"usuario": "Leo", "nota": 5},
                {"usuario": "Clara", "nota": 4}
            ]
        }
    ),
    (
        "Impressora EcoTank L3250",
        {
            "categoria": "impressora",
            "preco": 1100,
            "estoque": 7,
            "especificacoes": {
                "tipo": "multifuncional",
                "cor": True,
                "wifi": True
            },
            "tags": ["impressora", "wifi", "escritorio"],
            "avaliacoes": [
                {"usuario": "Sofia", "nota": 5}
            ]
        }
    ),
    (
        "Webcam HD Pro",
        {
            "categoria": "video",
            "preco": 210,
            "estoque": 33,
            "especificacoes": {
                "resolucao": "1080p",
                "microfone": True,
                "fps": 60
            },
            "tags": ["webcam", "videochamada", "hd"],
            "avaliacoes": [
                {"usuario": "Tais", "nota": 4}
            ]
        }
    ),
    (
        "Caixa de Som Pulse",
        {
            "categoria": "audio",
            "preco": 340,
            "estoque": 19,
            "especificacoes": {
                "potencia": "40W",
                "bluetooth": True,
                "portatil": True
            },
            "tags": ["caixa_som", "bluetooth", "musica"],
            "avaliacoes": [
                {"usuario": "Ruan", "nota": 5}
            ]
        }
    ),
    (
        "Cadeira Gamer Max",
        {
            "categoria": "moveis",
            "preco": 1450,
            "estoque": 6,
            "especificacoes": {
                "material": "couro sintetico",
                "ajuste_altura": True,
                "peso_max": "120kg"
            },
            "tags": ["cadeira", "gamer", "conforto"],
            "avaliacoes": [
                {"usuario": "Eli", "nota": 5},
                {"usuario": "Mila", "nota": 4}
            ]
        }
    ),
    (
        "HD Externo Backup 2TB",
        {
            "categoria": "armazenamento",
            "preco": 590,
            "estoque": 25,
            "especificacoes": {
                "tipo": "HD externo",
                "capacidade": "2TB",
                "usb": "3.0"
            },
            "tags": ["hd", "backup", "portatil"],
            "avaliacoes": [
                {"usuario": "Vitor", "nota": 4}
            ]
        }
    )
]

sql = """
INSERT INTO produtos (nome, detalhes)
VALUES (%s, %s::jsonb)
"""

for nome, detalhes in produtos:
    cur.execute(sql, (nome, json.dumps(detalhes)))

conn.commit()
print("14 produtos inseridos com sucesso!")

cur.execute("SELECT COUNT(*) FROM produtos;")
print("Total de produtos:", cur.fetchone()[0])

def executar_consulta(sql):
    cur.execute(sql)
    resultados = cur.fetchall()
    for linha in resultados:
        print(linha)
    print("-" * 60)

"""Consulta 1 — -> pega um valor do JSON como JSON"""

executar_consulta("""
SELECT nome, detalhes -> 'especificacoes'
FROM produtos;
""")

"""Consulta 2 — ->> pega um valor do JSON como texto"""

executar_consulta("""
SELECT nome, detalhes ->> 'categoria'
FROM produtos;
""")

"""Consulta 3 — #> pega um caminho dentro do JSON"""

executar_consulta("""
SELECT nome, detalhes #> '{especificacoes}'
FROM produtos;
""")

"""Consulta 4 — #>> pega o valor final em texto"""

executar_consulta("""
SELECT nome, detalhes #>> '{especificacoes,preco}'
FROM produtos;
""")

"""Consulta 5 — @> verifica contenção"""

executar_consulta("""
SELECT nome
FROM produtos
WHERE detalhes @> '{"categoria":"audio"}'::jsonb;
""")

"""Consulta 6 — <@ verifica contenção reversa"""

executar_consulta("""
SELECT nome
FROM produtos
WHERE '{"categoria":"audio"}'::jsonb <@ detalhes;
""")

"""Consulta 7 — ? verifica existência de chave"""

executar_consulta("""
SELECT nome
FROM produtos
WHERE detalhes ? 'tags';
""")

"""Consulta 8 — ?| verifica se existe pelo menos uma chave da lista"""

executar_consulta("""
SELECT nome
FROM produtos
WHERE detalhes ?| array['tags', 'avaliacoes'];
""")

"""Consulta 9 — ?& verifica se todas as chaves existem"""

executar_consulta("""
SELECT nome
FROM produtos
WHERE detalhes ?& array['tags', 'avaliacoes'];
""")

"""Consulta 10 — jsonb_path_exists e jsonb_path_query"""

executar_consulta("""
SELECT nome
FROM produtos
WHERE jsonb_path_exists(detalhes, '$.avaliacoes[*] ? (@.nota >= 5)');
""")

executar_consulta("""
SELECT nome, jsonb_path_query(detalhes, '$.avaliacoes[*].nota')
FROM produtos;
""")